version: "3.8"
services:
  builder:
    build:
      context: .
    volumes:
      - .:/app
    working_dir: /app
    user: "${UID:-1000}:${GID:-1000}"
    command: sh -c 'perl Makefile.PL && make dist && make zipdist'
